name: Publish
permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: |
          npm ci --omit=dev --no-audit --no-fund

      - name: Release
        run: npx semantic-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
