name: Publish Extension
permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Check version
        id: version
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   
      - name: Install dependencies
        if: version.outputs.changed == 'true'
        run: npm ci
      - name: Publish to Visual Studio Marketplace
        if: version.outputs.changed == 'true'
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
