name: Versioning
permissions:
  contents: write
  id-token: write
  pull-requests: write
  packages: write
  issues: write
on:
  pull_request:
    branches:
      - main

jobs:
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Generate release notes
        id: semantic-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_BRANCH: ${{ github.head_ref }}
        run: |
          GITHUB_REF=${{ env.GH_BRANCH }}
          git checkout $GITHUB_REF

          npx semantic-release --dry-run --no-ci --branches $GH_BRANCH > output.txt
          echo "releaseNote=$(cat output.txt | base64 -w 0)" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
      - name: Report Release Notes
        uses: actions/github-script@v7
        if: ${{ steps.semantic-release.outputs.releaseNote != '' }}
        env:
          RELEASE_NOTES_OUTPUT: ${{ steps.semantic-release.outputs.releaseNote }}
        with:
            script: |
              const { generateSummary } = await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/index.js`);
              return generateSummary({ context, github, core });
